

import {
    IconBuildingBank,
    IconCash,
    IconCategory,
    IconCheck,
    IconChevronDown,
    IconChevronLeft,
    IconChevronRight,
    IconClipboardList,
    IconCoins,
    IconCurrencyDollar,
    IconEdit,
    IconFileDollar,
    IconFileText,
    IconGraph,
    IconHome,
    IconInfoCircle,
    IconLock,
    IconLogout,
    IconMenu2,
    IconMoon,
    IconPackages,
    IconRotateClockwise,
    IconSearch,
    IconStar,
    IconSunHighFilled,
    IconTable,
    IconTrash,
    IconUsers,
    IconX,
    type Icon
} from '@tabler/icons-react';

export const ICON_MAP = {
    sun: IconSunHighFilled,
    moon: IconMoon,
    defaultMenuIcon: IconCategory,
    PmsoBusinessApp: IconCategory,
    home: IconHome,
    order: IconClipboardList,
    people: IconUsers,
    rotateLeft: IconRotateClockwise,
    chevronDown: IconChevronDown,
    chevronRight: IconChevronRight,
    chevronLeft: IconChevronLeft,
    bars: IconMenu2,
    form: IconFileText,
    star: IconStar,
    table: IconTable,
    search: IconSearch,
    close: IconX,
    lock: IconLock,
    info: IconInfoCircle,
    check: IconCheck,
    cash: IconCash,
    bank: IconBuildingBank,
    receivable: IconFileDollar,
    payable: IconCurrencyDollar,
    inventory: IconPackages,
    cost: IconCoins,
    report: IconGraph,
    category: IconCategory,
    logout: IconLogout,
    edit: IconEdit,
    delete: IconTrash,
} as const satisfies Record<string, Icon>;

export type IconKey = keyof typeof ICON_MAP;
