import type { JournalEntry } from "../type";

// users.mock.ts
export const users = [
    {
        id: 1,
        fullName: "Nguyen Van An",
        dob: "1988-03-12",
        gender: "Male",
        email: "an.nguyen@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 2,
        fullName: "Tran Thi Mai",
        dob: "1992-07-25",
        gender: "Female",
        email: "mai.tran@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Inactive",
    },
    {
        id: 3,
        fullName: "Le Quang Huy",
        dob: "1985-11-02",
        gender: "Male",
        email: "huy.le@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Inactive",
    },
    {
        id: 4,
        fullName: "Pham Thu Ha",
        dob: "1995-01-18",
        gender: "Female",
        email: "ha.pham@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Probation",
    },
    {
        id: 5,
        fullName: "Vo Minh Tuan",
        dob: "1980-09-30",
        gender: "Male",
        email: "tuan.vo@company.com",
        role: "Chief Financial Officer",
        department: "Executive",
        status: "Active",
    },
    {
        id: 6,
        fullName: "Do Anh Khoa",
        dob: "1990-05-14",
        gender: "Male",
        email: "khoa.do@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 7,
        fullName: "Bui Thi Lan",
        dob: "1993-08-09",
        gender: "Female",
        email: "lan.bui@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 8,
        fullName: "Dang Hoang Nam",
        dob: "1987-12-21",
        gender: "Male",
        email: "nam.dang@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 9,
        fullName: "Hoang Minh Chau",
        dob: "1996-04-05",
        gender: "Female",
        email: "chau.hoang@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 10,
        fullName: "Nguyen Duc Long",
        dob: "1984-10-11",
        gender: "Male",
        email: "long.nguyen@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Active",
    },
    {
        id: 11,
        fullName: "Tran Ngoc Anh",
        dob: "1991-06-17",
        gender: "Female",
        email: "anh.tran@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 12,
        fullName: "Pham Tien Dat",
        dob: "1989-02-28",
        gender: "Male",
        email: "dat.pham@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 13,
        fullName: "Le Thi Huong",
        dob: "1994-11-19",
        gender: "Female",
        email: "huong.le@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Inactive",
    },
    {
        id: 14,
        fullName: "Nguyen Thanh Phong",
        dob: "1982-01-07",
        gender: "Male",
        email: "phong.nguyen@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 15,
        fullName: "Vo Thi Kim Oanh",
        dob: "1990-09-03",
        gender: "Female",
        email: "oanh.vo@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 16,
        fullName: "Dang Quoc Viet",
        dob: "1986-05-26",
        gender: "Male",
        email: "viet.dang@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 17,
        fullName: "Tran Minh Tam",
        dob: "1997-12-01",
        gender: "Female",
        email: "tam.tran@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Probation",
    },
    {
        id: 18,
        fullName: "Le Hoai Nam",
        dob: "1983-08-14",
        gender: "Male",
        email: "nam.le@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Active",
    },
    {
        id: 19,
        fullName: "Pham Thi Thao",
        dob: "1992-03-22",
        gender: "Female",
        email: "thao.pham@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 20,
        fullName: "Nguyen Bao Khanh",
        dob: "1981-06-10",
        gender: "Male",
        email: "khanh.nguyen@company.com",
        role: "Chief Financial Officer",
        department: "Executive",
        status: "Active",
    },
    // 21–40 (similar realistic distribution)
    {
        id: 21,
        fullName: "Ho Thi Yen",
        dob: "1995-02-15",
        gender: "Female",
        email: "yen.ho@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 22,
        fullName: "Vu Thanh Tung",
        dob: "1988-07-08",
        gender: "Male",
        email: "tung.vu@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 23,
        fullName: "Nguyen My Linh",
        dob: "1993-10-27",
        gender: "Female",
        email: "linh.nguyen@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 24,
        fullName: "Pham Quang Hieu",
        dob: "1986-04-02",
        gender: "Male",
        email: "hieu.pham@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 25,
        fullName: "Tran Thi Bich",
        dob: "1991-09-11",
        gender: "Female",
        email: "bich.tran@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Inactive",
    },
    {
        id: 26,
        fullName: "Le Van Trung",
        dob: "1984-12-06",
        gender: "Male",
        email: "trung.le@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Active",
    },
    {
        id: 27,
        fullName: "Vo Thi Ngoc",
        dob: "1996-06-18",
        gender: "Female",
        email: "ngoc.vo@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Probation",
    },
    {
        id: 28,
        fullName: "Dang Minh Quan",
        dob: "1989-01-29",
        gender: "Male",
        email: "quan.dang@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 29,
        fullName: "Nguyen Thi Tuyet",
        dob: "1994-05-07",
        gender: "Female",
        email: "tuyet.nguyen@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 30,
        fullName: "Le Duc Thinh",
        dob: "1982-11-16",
        gender: "Male",
        email: "thinh.le@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 31,
        fullName: "Pham Hong Nhung",
        dob: "1997-03-03",
        gender: "Female",
        email: "nhung.pham@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 32,
        fullName: "Vu Manh Cuong",
        dob: "1985-08-19",
        gender: "Male",
        email: "cuong.vu@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Active",
    },
    {
        id: 33,
        fullName: "Tran Thu Trang",
        dob: "1992-12-24",
        gender: "Female",
        email: "trang.tran@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 34,
        fullName: "Nguyen Van Phuc",
        dob: "1980-02-09",
        gender: "Male",
        email: "phuc.nguyen@company.com",
        role: "Chief Financial Officer",
        department: "Executive",
        status: "Active",
    },
    {
        id: 35,
        fullName: "Le Thi Minh",
        dob: "1995-07-13",
        gender: "Female",
        email: "minh.le@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 36,
        fullName: "Pham Huu Loc",
        dob: "1987-10-05",
        gender: "Male",
        email: "loc.pham@company.com",
        role: "Senior Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 37,
        fullName: "Vo Thi Thanh",
        dob: "1993-01-20",
        gender: "Female",
        email: "thanh.vo@company.com",
        role: "Accountant",
        department: "Finance",
        status: "Active",
    },
    {
        id: 38,
        fullName: "Dang Tuan Kiet",
        dob: "1984-06-28",
        gender: "Male",
        email: "kiet.dang@company.com",
        role: "Auditor",
        department: "Internal Audit",
        status: "Active",
    },
    {
        id: 39,
        fullName: "Nguyen Phuong Linh",
        dob: "1996-09-02",
        gender: "Female",
        email: "linh.phuong@company.com",
        role: "Junior Accountant",
        department: "Finance",
        status: "Probation",
    },
    {
        id: 40,
        fullName: "Tran Duc Minh",
        dob: "1981-04-17",
        gender: "Male",
        email: "minh.tran@company.com",
        role: "Accounting Manager",
        department: "Finance",
        status: "Active",
    },
];

export const journalEntries: JournalEntry[] = [
    {
        id: "JE001",
        date: "2025-01-01",
        documentNo: "DOC-2025-001",
        account: "111",
        amount: 5000000,
        department: "ADMIN",
        property: ["Debit"],
        note: "Initial cash balance",
    },
    {
        id: "JE002",
        date: "2025-01-02",
        documentNo: "DOC-2025-002",
        account: "411",
        amount: 5000000,
        department: "ADMIN",
        property: ["Credit"],
        note: "Capital contribution",
    },
    {
        id: "JE003",
        date: "2025-01-03",
        documentNo: "DOC-2025-003",
        account: "642",
        amount: 1200000,
        department: "ADMIN",
        property: ["Debit"],
        note: "Office supplies",
    },
    {
        id: "JE004",
        date: "2025-01-03",
        documentNo: "DOC-2025-004",
        account: "111",
        amount: 1200000,
        department: "ADMIN",
        property: ["Credit"],
        note: "Paid office supplies",
    },
    {
        id: "JE005",
        date: "2025-01-04",
        documentNo: "DOC-2025-005",
        account: "131",
        amount: 8000000,
        department: "SALES",
        property: ["Debit"],
        note: "Invoice issued to customer A",
    },
    {
        id: "JE006",
        date: "2025-01-04",
        documentNo: "DOC-2025-006",
        account: "511",
        amount: 8000000,
        department: "SALES",
        property: ["Credit"],
        note: "Revenue from customer A",
    },
    {
        id: "JE007",
        date: "2025-01-05",
        documentNo: "DOC-2025-007",
        account: "632",
        amount: 4500000,
        department: "SALES",
        property: ["Debit"],
        note: "COGS for invoice",
    },
    {
        id: "JE008",
        date: "2025-01-05",
        documentNo: "DOC-2025-008",
        account: "156",
        amount: 4500000,
        department: "MARKETING",
        property: ["Credit"],
        note: "Inventory issued",
    },
];

// auto-generate more rows (up to 30)
while (journalEntries.length < 30) {
    const i = journalEntries.length + 1;
    journalEntries.push({
        id: `JE${String(i).padStart(3, "0")}`,
        date: "2025-01-06",
        documentNo: `DOC-2025-${String(i).padStart(3, "0")}`,
        account: i % 2 === 0 ? "111" : "642",
        amount: 300000 + i * 10000,
        department: i % 2 === 0 ? "ADMIN" : "IT",
        property: i % 2 === 0 ? ["Credit"] : ["Debit"],
        note: "Auto generated entry",
    });
}
